import type { PhysicalFacility, SchoolService, Activity, ForeignLanguage } from "../../types";

export const FACILITY_LABELS: Record<PhysicalFacility, string> = {
  UykuOdasi: "Uyku Odası",
  Yemekhane: "Yemekhane",
  Havuz: "Havuz",
  BilgisayarLaboratorivari: "Bilgisayar Laboratuvarı",
  KapalISporSalonu: "Kapalı Spor Salonu",
  FutbolSahasi: "Futbol Sahası",
  KonferansSalonu: "Konferans Salonu",
  Laboratorivari: "Laboratuvarı",
  SanatAtoliyesi: "Sanat Atölyesi",
  Kantin: "Kantin",
  Kutupahane: "Kütüphane",
  MuzikOdasi: "Müzik Odası",
  OyunAlani: "Oyun Alanı",
  Revir: "Revir",
  Bahce: "Bahçe",
  Lojman: "Lojman",
  AkillTahta: "Akıllı Tahta",
  HayvanatBahcesi: "Hayvanat Bahçesi",
  Sera: "Sera",
  IcBoyutluOdasi: "İç Boyutlu Odası",
  MutfakAtoliyesi: "Mutfak Atölyesi",
  SporAlani: "Spor Alanı",
  KumHavuzu: "Kum Havuzu",
};

export const SERVICE_LABELS: Record<SchoolService, string> = {
  Guvenlik: "Güvenlik",
  Rehberlik: "Rehberlik",
  YazOkulu: "Yaz Okulu",
  Servis: "Servis",
  HaftasonuEgitim: "Hafta Sonu Eğitim",
  OrganikBeslenme: "Organik Beslenme",
  OyunGrubu: "Oyun Grubu",
  AnneCocukOyunGrubu: "Anne-Çocuk Oyun Grubu",
  DiniEgitim: "Dini Eğitim",
};

export const ACTIVITY_LABELS: Record<Activity, string> = {
  Futbol: "Futbol",
  Voleybol: "Voleybol",
  Basketbol: "Basketbol",
  Judo: "Judo",
  MasaTenisi: "Masa Tenisi",
  SuTopu: "Su Topu",
  Fotografcilik: "Fotoğrafçılık",
  Satranc: "Satranç",
  Yuzme: "Yüzme",
  Seramik: "Seramik",
  Bale: "Bale",
  Origami: "Origami",
  Hentbol: "Hentbol",
  Sinema: "Sinema",
  SuBalesi: "Su Balesi",
  DekoratifSanatlar: "Dekoratif Sanatlar",
  YabancıDilKlubu: "Yabancı Dil Kulübü",
  Heykel: "Heykel",
  Muzik: "Müzik",
  ModernDans: "Modern Dans",
  Tenis: "Tenis",
  Drama: "Drama",
  GoruselSanatlar: "Görüsel Sanatlar",
  Tiyatro: "Tiyatro",
  Eskrim: "Eskrim",
  Gures: "Güreş",
  Ebru: "Ebru",
  Izcilik: "İzcilik",
  Atletizm: "Atletizm",
  Binicilik: "Binicilik",
  Okculuk: "Okçuluk",
  Proje: "Proje",
  BuzPateni: "Buz Pateni",
  Gezi: "Gezi",
  Tirmanis: "Tırmanış",
  Perkusyon: "Perkusyon",
  Piyano: "Piyano",
  IngilizzeDrama: "İngilizce Drama",
  BilisimKlubu: "Bilişim Kulübü",
  Gazetecilik: "Gazetecilik",
  Orkestra: "Orkestra",
  Koro: "Koro",
  Jimnastik: "Jimnastik",
  Ekoloji: "Ekoloji",
  HalkOyunlari: "Halk Oyunları",
  Dans: "Dans",
  AkilVeZekaOyunlari: "Akıl ve Zeka Oyunları",
  Yoga: "Yoga",
  ElSanatlari: "El Sanatları",
  DegerlerEgitimi: "Değerler Eğitimi",
  Orff: "Orff",
  PlanetariumGokBilimi: "Planetarium Gök Bilimi",
  Robotik: "Robotik",
  Badminton: "Badminton",
  BedEnEgitimi: "Beden Eğitimi",
  Taekwondo: "Taekwondo",
  Gitar: "Gitar",
  Karate: "Karate",
  Pilates: "Pilates",
  ESpor: "E-Spor",
  Kodlama: "Kodlama",
};

export const LANGUAGE_LABELS: Record<ForeignLanguage, string> = {
  Ingilizce: "İngilizce",
  Almanca: "Almanca",
  Francizca: "Fransızca",
  Ispanyolca: "İspanyolca",
  Italyanca: "İtalyanca",
  Cinece: "Çince",
  Ruscaj: "Rusça",
  Arapca: "Arapça",
  Japonica: "Japonca",
  Ibrahimce: "İbrahimce",
  Ermenice: "Ermenice",
  Ukraynaca: "Ukraynaca",
};
